<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'adminquickbar\\admin\\adminquickbaradmin' => '/Admin/AdminQuickbarAdmin.php',
                'adminquickbar\\lib\\activator' => '/Lib/Activator.php',
                'adminquickbar\\lib\\adminquickbar' => '/Lib/AdminQuickbar.php',
                'adminquickbar\\lib\\deactivator' => '/Lib/Deactivator.php',
                'adminquickbar\\lib\\i18n' => '/Lib/I18N.php',
                'adminquickbar\\lib\\loader' => '/Lib/Loader.php',
                'adminquickbar\\lib\\settings' => '/Lib/Settings.php',
                'adminquickbar\\lib\\sidebar' => '/Lib/Sidebar.php',
                'adminquickbar\\lib\\sidebar\\contextmenu' => '/Lib/Sidebar/ContextMenu.php',
                'adminquickbar\\lib\\sidebar\\render' => '/Lib/Sidebar/Render.php',
                'adminquickbar\\lib\\sidebar\\wpml' => '/Lib/Sidebar/Wpml.php',
                'adminquickbar\\lib\\template' => '/Lib/Template.php',
                'adminquickbar\\lib\\toolbar' => '/Lib/Toolbar.php',
                'adminquickbar\\pub\\adminquickbarpublic' => '/Public/AdminQuickbarPublic.php',
                'composer\\autoload\\classloader' => '/vendor/composer/ClassLoader.php',
                'composer\\autoload\\composerstaticinitf76597d2b49de9e09c4c59954bae0f13' => '/vendor/composer/autoload_static.php',
                'composerautoloaderinitf76597d2b49de9e09c4c59954bae0f13' => '/vendor/composer/autoload_real.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
